// <auto-generated />
namespace EDeviceClaims.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createClaimEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createClaimEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201603181341527_createClaimEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
